apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: redisdepoyment
  labels:
    name: redispod
spec:
  template:
    metadata: 
      name: redispod
      labels:
        name: redispodlabel
    spec:
      containers:
      - name: redispod
        image: redis
       
  replicas: 2
  selector:
    matchLabels:
      name: redispodlabel


